source "http://rubygems.org"
ruby "2.4.0"

# in your Gemfile
gem 'activerecord'
# the actual ActiveRecord library
gem 'sinatra'
gem 'sinatra-activerecord'
# the adapter between Sinatra and
# the ActiveRecord library
gem 'sqlite3'
# the database adapter to use the
# sqlite3 db system with ActiveRecord
gem 'rake'
